
- name: Deploy Java project to AWS EC2
  hosts: all
  gather_facts: false
  tasks:
    - name: Provision EC2 instances
      ec2:
        key_name: "my-key1"
        instance_type: "t3.micro"
        image: "ami-0014ce3e52359afbd"
        wait: true
        count: 2
        region: "eu-north-1"
        group: "MySecurityGroup"
        assign_public_ip: yes
      register: ec2

    - name: Add build and deploy instances to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        group: "{{ item.tags.Name }}"
      with_items: "{{ ec2.tagged_instances }}"

- name: Install and configure software
  hosts: all
  become: true
  serial: 1
  tasks:
    - name: Install git
      package:
        name: git
        state: present

    - name: Install Java
      package:
        name: openjdk-11-jdk
        state: present

    - name: Install Tomcat
      package:
        name: tomcat9
        state: present

    - name: Install Maven
      package:
        name: maven
        state: present

- name: Build and deploy Java application
  hosts: build
  gather_facts: false
  become: true
  tasks:
    - name: Clone project repository
      git:
        repo: https://github.com/Stupin87/boxfuse1.git
        dest: /home/ubuntu/boxfuse1

    - name: Build Java project with Maven
      shell: mvn clean install
      args:
        chdir: /home/ubuntu/boxfuse1

    - name: Transfer artifact to production node
      synchronize:
        src: /home/ubuntu/boxfuse1/target/hello-1.0.war
        dest: /home/ubuntu/
        mode: 'u+rwx,g+rx,o+rx'

- name: Copy WAR file to Tomcat webapps
  hosts: production
  become: true
  tasks:
    - name: Copy WAR file to Tomcat webapps
      copy:
        src: /home/ubuntu/boxfuse1/target/hello-1.0.war
        dest: /usr/local/tomcat/webapps

